### ISSUE TITLE
Neos 7.x compatibility

### ISSUE THREAD

**Issue by paavo** [flownative/neos-workspace-preview#11]
Currently – as per `composer.json` – this package is not compatible with Neos 7. 
Therefore we need to check / fix / update it.

**Comment by paavo** [comment]
Are there any plans to update neos-workspace-preview to Support Neos 7 @kdambekalns ?

**Comment by kdambekalns** [comment]
Not by me right now (and probably not "by itself" before July)… But @kitsunet would be the one to judge potential problems and the effort needed.

Does it work, @paavo? You could simply try to clone it into a Neos 7 project and check… maybe a `composer.json` change is all that's needed?

**Comment by paavo** [comment]
Let me try this in the next Neos 7 project in the next weeks @kdambekalns ..

**Comment by kdambekalns** [comment]
@paavo Did you get to try this?

**Comment by paavo** [comment]
> @paavo Did you get to try this?
Not yet, im sorry.

**Comment by jobee** [comment]
I've tried it, help appreciated in #23

**Comment by kdambekalns** [comment]
See https://github.com/flownative/neos-workspace-preview/releases/tag/v2.1.0 – thanks to @jobee.
