### ISSUE TITLE
Neos 5.x compatibility

### ISSUE THREAD

**Issue by robertlemke** [flownative/neos-workspace-preview#2]
Currently – as per `composer.json` – this package is not compatible with Neos 5. Therefore we need to check / fix / update it.

**Comment by paxuclus** [comment]
Hi @robertlemke,

I have opened a Draft for Neos 5 support: #6. So far it seems to work fine, but I did not thoroughly test it yet.

**Comment by paavo** [comment]
Did you had any luck testing this with Neos 5? @nlx-lars

**Comment by paxuclus** [comment]
Hi @paavo,

my patch (#6) has been on production for about two weeks with Neos 5.2 now, I haven't heard any negative feedback from my client so far. I'm guessing it works fine.

**Comment by paavo** [comment]
Any plans when this PR will be reviewed @robertlemke ?
Have a good week 👋

**Comment by paxuclus** [comment]
Since [2.0.0](https://github.com/flownative/neos-workspace-preview/releases/tag/2.0.0) this package supports 5.X.

@robertlemke I guess this issue can be closed now?

**Comment by bwaidelich** [comment]
Yes, I can confirm that it works with Neos 5.3
